
OBJS = ofmo-falanx-main.o 	\
		ofmo-storage.o		\
		ofmo-datastore.o 	\
		ofmo-monomer-data.o \
		ofmo-mserv-cont.o	\
		ofmo-task-util.o 	\
		ofmo-worker-task.o


all: ${OBJS}

clean:
	-rm -f ${OBJS}

